server:
  port: 8093
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_orders
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql

product:
  service:
    url: http://localhost:8091/api/v1/products
user:
  service:
    url: http://localhost:8092/api/v1/users